[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-lib"
version = "0.1.0"
description = "Demo Python library"
authors = [
    { name="Your Name", email="you@example.com" }
]
readme = "README.md"
